### ISSUE TITLE
Misalignment when using grouped columns and column size < 20px

### ISSUE THREAD

**Issue by alexander-alvarez** [offirgolan/ember-light-table#287]
As demonstrated in (https://github.com/offirgolan/ember-light-table/compare/master...alexander-alvarez:no-label-header ):
![image](https://cloud.githubusercontent.com/assets/11779993/21194305/6d7e00bc-c1fd-11e6-8873-128f2853f434.png)

haven't traced the source, but wanted to demonstrate it in case anyone knew

**Comment by offirgolan** [comment]
@alexander-alvarez I haven't had a chance to dig much into this but could this just be a CSS issue?

```css
.grouped-table .lt-row  .lt-cell:first-of-type:before {
  counter-increment: row-counter;
  content: counter(row-counter);
  margin: -10px;
}
```

The margin + content on the `before` pseudo element could be screwing up with the table's alignment. Again, just a thought... I haven't run into this sort of issue before.
