### ISSUE TITLE
"nowrap" attribute to table cells

### ISSUE THREAD

**Issue by nelnico** [offirgolan/ember-light-table#411]
Not always knowing how much content a cell will hold (be it a header or body cell) it would be nice to be able to add a "nowrap" attribute to the columns.

I checked the source and there seem to be an attributeBindings, but setting it seems to have no effect?  (not added to table's dom)

**Comment by buschtoens** [comment]
That's something you would control with CSS. 

```css
.nowrap {
  overflow: hidden;
  text-overflow: hidden;
}
```

That class can be applied via [`Column.cellClassNames`](http://offirgolan.github.io/ember-light-table/docs/classes/Column.html#property_cellClassNames).

**Comment by buschtoens** [comment]
Oops, didn't have my wake up coffee yet. The snippet above was missing something. Edited it. 🙂

**Comment by nelnico** [comment]
Got that right (needed both className and cellClassNames it seems), but realized one can add  a c lass to the table itself.  
Will see tomorrow if can do it that way, eliminating 2 entries for each of my nearly 1000 columns (spread over several tables of course)

**Comment by buschtoens** [comment]
1000 columns? 😨 Wow. 😅

If you need all of these columns to not wrap, I would suggest doing something like this:

```css
.table--nowrap .lt-cell {
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}
```

```hbs
{{#light-table table class"table--nowrap" as |t|}}
  ...
{{/light-table}}
```

`.lt-cell` is automatically applied to every cell by default.
