### ISSUE TITLE
How to CSS rowComponent  

### ISSUE THREAD

**Issue by kmichek** [offirgolan/ember-light-table#507]
I would like to set row selected and row hover styles on `#t.body rowComponent=(component 'colored-row')`, similar to regular line styles:

```css
.ember-light-table .lt-row.is-selected {
    background-color: #DEDEDE; /* <-- this */
}
.ember-light-table .lt-row:not(.is-selected):hover {
    background-color: #F5F4F4; /* <-- and this one */
}
```

Is that possible, please? Thank you.

**Comment by alexander-alvarez** [comment]
hey @kmichek, can you help clarify what you're trying to achieve?
what's your current setup? do you have a custom row component?

styling can be achieved implementing css to target the selectors that you want to style -- are you having trouble finding specific selectors?

**Comment by kmichek** [comment]
hi. yes I have a custom row component, copied it from the tutorial, and I'm having trouble finding specific selectors. I tried to tweak
.ember-light-table .lt-row.colored-row {color: #fff}
.ember-light-table .lt-row.colored-row:hover {opacity: .8}
changing the styles for regulard rows as described above works fine, but I cannot figure how to modify colours for the custom ones. I know it's my lack of css knowledge. 
thanks

**Comment by buschtoens** [comment]
When using a custom row component, you can use [`classNameBindings`](https://www.emberjs.com/api/ember/2.16/classes/Component/properties/classNameBindings?anchor=classNameBindings) to add custom CSS classes depending on the component state, e.g. `isSelected`.

**Comment by buschtoens** [comment]
For example:

```js
import Component from '@ember/component';
import { reads } from '@ember/object/computed';

export default Component.extend({
  classNameBindings: ['isSelected'],

  isSelected: reads('row.selected')
});
```

If I may recommend a good addon for CSS on a per component basis: [ember-css-modules](https://github.com/salsify/ember-css-modules)

With ember-css-modules installed you could go:

```js
// app/components/foo-row/component.js
import Component from '@ember/component';
import { reads } from '@ember/object/computed';

export default Component.extend({
  localClassNameBindings: ['isSelected'],

  isSelected: reads('row.selected')
});
```

```css
// app/components/foo-row/styles.css
.is-selected {
  background: yellow;
}
```
